--------------------------------------------------------
--  File created - Tuesday-November-10-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence FTP_EXCEPTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FTPSERVERU"."FTP_EXCEPTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999 INCREMENT BY 1 START WITH 130 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FTP_JOB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FTPSERVERU"."FTP_JOB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 91 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FTP_USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FTPSERVERU"."FTP_USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table FTP_EXCEPTIONS
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."FTP_EXCEPTIONS" 
   (	"EXCEPTION_ID" NUMBER, 
	"EXCEPTION_DETAILS" VARCHAR2(4000 BYTE), 
	"JOB_ID" NUMBER, 
	"LOG_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FTP_JOB
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."FTP_JOB" 
   (	"JOB_ID" NUMBER(*,0), 
	"JOB_NAME" VARCHAR2(45 BYTE), 
	"CRON_EXP" VARCHAR2(33 BYTE), 
	"SRC_SERVER_URL" VARCHAR2(55 BYTE), 
	"SRC_SERVER_USER" VARCHAR2(33 BYTE), 
	"SRC_SERVER_PASS" VARCHAR2(33 BYTE), 
	"SRC_SERVER_PATH" VARCHAR2(200 BYTE), 
	"DEST_SERVER_URL" VARCHAR2(200 BYTE), 
	"DEST_SERVER_USER" VARCHAR2(33 BYTE), 
	"DEST_SERVER_PASS" VARCHAR2(33 BYTE), 
	"DEST_SERVER_PATH" VARCHAR2(200 BYTE), 
	"DEST_SECURE_CON" NUMBER(*,0), 
	"STATUS" NUMBER(*,0) DEFAULT -1, 
	"USER_ID" NUMBER, 
	"SRC_SECURE_CON" NUMBER, 
	"POST_FTP_OPTION" NUMBER DEFAULT 0, 
	"SRC_BACKUP_DIR" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 

   COMMENT ON COLUMN "FTPSERVERU"."FTP_JOB"."STATUS" IS '-1 notstarted , 0 stopped , 1 running  job , 2 updatde , 4 run wiz err
';
 
   COMMENT ON COLUMN "FTPSERVERU"."FTP_JOB"."POST_FTP_OPTION" IS '0 no action - 1 delete after copying  - 2 move to backup folder
';
--------------------------------------------------------
--  DDL for Table FTP_JOB_USER_MAPPING
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."FTP_JOB_USER_MAPPING" 
   (	"JOB_USER_MAPPING_ID" NUMBER, 
	"USER_ID" NUMBER(*,0), 
	"JOB_ID" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FTP_USER_TABLE
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."FTP_USER_TABLE" 
   (	"USER_ID" NUMBER(*,0), 
	"USERNAME" VARCHAR2(33 BYTE), 
	"PASSWORD" VARCHAR2(33 BYTE), 
	"USER_TYPE_ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FTP_USER_TYPE
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."FTP_USER_TYPE" 
   (	"USER_TYPE_ID" NUMBER(*,0), 
	"USER_TYPE_NAME" VARCHAR2(45 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STG_MASTER
--------------------------------------------------------

  CREATE TABLE "FTPSERVERU"."STG_MASTER" 
   (	"OFFER_ID" NUMBER, 
	"EXTERNAL_OFFER_ID" VARCHAR2(100 BYTE), 
	"CAMPAIGN_ID" VARCHAR2(1000 BYTE), 
	"LIFECYCLE_ID" NUMBER, 
	"EXTERNAL_SERVICE_ID" VARCHAR2(100 BYTE), 
	"SERVICE_ID" NUMBER, 
	"RP_ID" NUMBER, 
	"RPA_CATEGORY" NUMBER, 
	"RESTRICTION_CATEGORY" NUMBER, 
	"IS_PDP" NUMBER, 
	"QUOTA_AMOUNT" VARCHAR2(1000 BYTE), 
	"TYPE" NUMBER, 
	"STATUS" NUMBER DEFAULT 0, 
	"CANCELLATION_POLICY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_EXCEPTIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_EXCEPTIONS_PK" ON "FTPSERVERU"."FTP_EXCEPTIONS" ("EXCEPTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_JOB_NAME_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_JOB_NAME_UK1" ON "FTPSERVERU"."FTP_JOB" ("JOB_NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_JOB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_JOB_PK" ON "FTPSERVERU"."FTP_JOB" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_JOB_USER_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_JOB_USER_MAPPING_PK" ON "FTPSERVERU"."FTP_JOB_USER_MAPPING" ("JOB_USER_MAPPING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_USER_TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_USER_TABLE_PK" ON "FTPSERVERU"."FTP_USER_TABLE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FTP_USER_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FTPSERVERU"."FTP_USER_TYPE_PK" ON "FTPSERVERU"."FTP_USER_TYPE" ("USER_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FTP_EXCEPTIONS
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" ADD CONSTRAINT "FTP_EXCEPTIONS_PK" PRIMARY KEY ("EXCEPTION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" MODIFY ("EXCEPTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" MODIFY ("EXCEPTION_DETAILS" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" MODIFY ("JOB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" MODIFY ("LOG_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FTP_JOB
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_JOB" ADD CONSTRAINT "FTP_JOB_NAME_UK1" UNIQUE ("JOB_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB" ADD CONSTRAINT "FTP_JOB_PK" PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB" MODIFY ("JOB_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB" MODIFY ("JOB_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB" MODIFY ("POST_FTP_OPTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FTP_JOB_USER_MAPPING
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_JOB_USER_MAPPING" ADD CONSTRAINT "FTP_JOB_USER_MAPPING_PK" PRIMARY KEY ("JOB_USER_MAPPING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB_USER_MAPPING" MODIFY ("JOB_USER_MAPPING_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FTP_USER_TABLE
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" ADD CONSTRAINT "FTP_USER_TABLE_PK" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" MODIFY ("PASSWORD" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" MODIFY ("USER_TYPE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FTP_USER_TYPE
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_USER_TYPE" ADD CONSTRAINT "FTP_USER_TYPE_PK" PRIMARY KEY ("USER_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TYPE" MODIFY ("USER_TYPE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "FTPSERVERU"."FTP_USER_TYPE" MODIFY ("USER_TYPE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table FTP_EXCEPTIONS
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_EXCEPTIONS" ADD CONSTRAINT "FTP_EXCEPTIONS_JOB_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "FTPSERVERU"."FTP_JOB" ("JOB_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FTP_JOB
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_JOB" ADD CONSTRAINT "JOB_USR_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "FTPSERVERU"."FTP_USER_TABLE" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FTP_JOB_USER_MAPPING
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_JOB_USER_MAPPING" ADD CONSTRAINT "FTP_JOB_USER_MAPPING_FK1" FOREIGN KEY ("JOB_ID")
	  REFERENCES "FTPSERVERU"."FTP_JOB" ("JOB_ID") ENABLE;
 
  ALTER TABLE "FTPSERVERU"."FTP_JOB_USER_MAPPING" ADD CONSTRAINT "FTP_JOB_USER_MAPPING_FK2" FOREIGN KEY ("USER_ID")
	  REFERENCES "FTPSERVERU"."FTP_USER_TABLE" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FTP_USER_TABLE
--------------------------------------------------------

  ALTER TABLE "FTPSERVERU"."FTP_USER_TABLE" ADD CONSTRAINT "USER_TYPE_FK1" FOREIGN KEY ("USER_TYPE_ID")
	  REFERENCES "FTPSERVERU"."FTP_USER_TYPE" ("USER_TYPE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger FTP_EXCEPTIONS_AUT_INCR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FTPSERVERU"."FTP_EXCEPTIONS_AUT_INCR" 
BEFORE INSERT ON FTP_EXCEPTIONS 
FOR EACH ROW
BEGIN
  SELECT FTP_EXCEPTION_SEQ.nextval  INTO :NEW.EXCEPTION_ID FROM DUAL;
END;				 
				
/
ALTER TRIGGER "FTPSERVERU"."FTP_EXCEPTIONS_AUT_INCR" ENABLE;
--------------------------------------------------------
--  DDL for Trigger JOB_AUTO_INCREMENT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FTPSERVERU"."JOB_AUTO_INCREMENT" 
BEFORE INSERT ON FTP_JOB 
FOR EACH ROW
BEGIN
  SELECT FTP_JOB_SEQ.nextval  INTO :NEW.JOB_ID FROM DUAL;
END;
/
ALTER TRIGGER "FTPSERVERU"."JOB_AUTO_INCREMENT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FTPSERVERU"."TRIGGER1" 
BEFORE INSERT ON FTP_JOB 
FOR EACH ROW
BEGIN
  SELECT FTP_JOB_SEQ.nextval  INTO :NEW.JOB_ID FROM DUAL;
END;
/
ALTER TRIGGER "FTPSERVERU"."TRIGGER1" DISABLE;
--------------------------------------------------------
--  DDL for Trigger TRIGGER2
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FTPSERVERU"."TRIGGER2" 
BEFORE INSERT ON FTP_EXCEPTIONS 
FOR EACH ROW
BEGIN
  SELECT FTP_EXCEPTION_SEQ.nextval  INTO :NEW.EXCEPTION_ID FROM DUAL;
END;				 
				
/
ALTER TRIGGER "FTPSERVERU"."TRIGGER2" DISABLE;
