package com.shaah.vouch_status.hibernatebeans;
// Generated Mar 10, 2015 12:13:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * FtpExceptions generated by hbm2java
 */
public class FtpExceptions  implements java.io.Serializable {


     private BigDecimal exceptionId;
     private FtpJob ftpJob;
     private String exceptionDetails;
     private Date logDate;

    public FtpExceptions() {
    }

    public FtpExceptions(BigDecimal exceptionId, FtpJob ftpJob, String exceptionDetails, Date logDate) {
       this.exceptionId = exceptionId;
       this.ftpJob = ftpJob;
       this.exceptionDetails = exceptionDetails;
       this.logDate = logDate;
    }
   
    public BigDecimal getExceptionId() {
        return this.exceptionId;
    }
    
    public void setExceptionId(BigDecimal exceptionId) {
        this.exceptionId = exceptionId;
    }
    public FtpJob getFtpJob() {
        return this.ftpJob;
    }
    
    public void setFtpJob(FtpJob ftpJob) {
        this.ftpJob = ftpJob;
    }
    public String getExceptionDetails() {
        return this.exceptionDetails;
    }
    
    public void setExceptionDetails(String exceptionDetails) {
        this.exceptionDetails = exceptionDetails;
    }
    public Date getLogDate() {
        return this.logDate;
    }
    
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }




}


