package com.shaah.vouch_status.hibernatebeans;
// Generated Mar 10, 2015 12:13:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * FtpJobUserMapping generated by hbm2java
 */
public class FtpJobUserMapping  implements java.io.Serializable {


     private BigDecimal jobUserMappingId;
     private FtpUserTable ftpUserTable;
     private FtpJob ftpJob;

    public FtpJobUserMapping() {
    }

	
    public FtpJobUserMapping(BigDecimal jobUserMappingId) {
        this.jobUserMappingId = jobUserMappingId;
    }
    public FtpJobUserMapping(BigDecimal jobUserMappingId, FtpUserTable ftpUserTable, FtpJob ftpJob) {
       this.jobUserMappingId = jobUserMappingId;
       this.ftpUserTable = ftpUserTable;
       this.ftpJob = ftpJob;
    }
   
    public BigDecimal getJobUserMappingId() {
        return this.jobUserMappingId;
    }
    
    public void setJobUserMappingId(BigDecimal jobUserMappingId) {
        this.jobUserMappingId = jobUserMappingId;
    }
    public FtpUserTable getFtpUserTable() {
        return this.ftpUserTable;
    }
    
    public void setFtpUserTable(FtpUserTable ftpUserTable) {
        this.ftpUserTable = ftpUserTable;
    }
    public FtpJob getFtpJob() {
        return this.ftpJob;
    }
    
    public void setFtpJob(FtpJob ftpJob) {
        this.ftpJob = ftpJob;
    }




}


