package com.shaah.vouch_status.hibernatebeans;
// Generated Mar 10, 2015 12:13:12 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * FtpJob generated by hbm2java
 */
public class FtpJob  implements java.io.Serializable {


     private BigDecimal jobId;
     private FtpUserTable ftpUserTable;
     private String jobName;
     private String cronExp;
     private String srcServerUrl;
     private String srcServerUser;
     private String srcServerPass;
     private String srcServerPath;
     private String destServerUrl;
     private String destServerUser;
     private String destServerPass;
     private String destServerPath;
     private String srcBckupDir;
     private BigDecimal destSecureCon;
     private BigDecimal status;
     private BigDecimal postFTPOpt;
     private BigDecimal srcSecureCon;
     private Set ftpJobUserMappings = new HashSet(0);
     private Set ftpExceptionses = new HashSet(0);

    public FtpJob() {
    }

	
    public FtpJob(BigDecimal jobId, FtpUserTable ftpUserTable, String jobName) {
        this.jobId = jobId;
        this.ftpUserTable = ftpUserTable;
        this.jobName = jobName;
    }
    public FtpJob(BigDecimal jobId, FtpUserTable ftpUserTable, String jobName, String cronExp, String srcServerUrl, String srcServerUser, String srcServerPass, String srcServerPath, String destServerUrl, String destServerUser, String destServerPass, String destServerPath, BigDecimal destSecureCon, BigDecimal status, BigDecimal srcSecureCon, Set ftpJobUserMappings, Set ftpExceptionses) {
       this.jobId = jobId;
       this.ftpUserTable = ftpUserTable;
       this.jobName = jobName;
       this.cronExp = cronExp;
       this.srcServerUrl = srcServerUrl;
       this.srcServerUser = srcServerUser;
       this.srcServerPass = srcServerPass;
       this.srcServerPath = srcServerPath;
       this.destServerUrl = destServerUrl;
       this.destServerUser = destServerUser;
       this.destServerPass = destServerPass;
       this.destServerPath = destServerPath;
       this.destSecureCon = destSecureCon;
       this.status = status;
       this.srcSecureCon = srcSecureCon;
       this.ftpJobUserMappings = ftpJobUserMappings;
       this.ftpExceptionses = ftpExceptionses;
    }
   
    
    
    public String getSrcBckupDir() {
		return srcBckupDir;
	}


	public void setSrcBckupDir(String srcBckupDir) {
		this.srcBckupDir = srcBckupDir;
	}


	public BigDecimal getPostFTPOpt() {
		return postFTPOpt;
	}


	public void setPostFTPOpt(BigDecimal postFTPOpt) {
		this.postFTPOpt = postFTPOpt;
	}


	public BigDecimal getJobId() {
        return this.jobId;
    }
    
    public void setJobId(BigDecimal jobId) {
        this.jobId = jobId;
    }
    public FtpUserTable getFtpUserTable() {
        return this.ftpUserTable;
    }
    
    public void setFtpUserTable(FtpUserTable ftpUserTable) {
        this.ftpUserTable = ftpUserTable;
    }
    public String getJobName() {
        return this.jobName;
    }
    
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }
    public String getCronExp() {
        return this.cronExp;
    }
    
    public void setCronExp(String cronExp) {
        this.cronExp = cronExp;
    }
    public String getSrcServerUrl() {
        return this.srcServerUrl;
    }
    
    public void setSrcServerUrl(String srcServerUrl) {
        this.srcServerUrl = srcServerUrl;
    }
    public String getSrcServerUser() {
        return this.srcServerUser;
    }
    
    public void setSrcServerUser(String srcServerUser) {
        this.srcServerUser = srcServerUser;
    }
    public String getSrcServerPass() {
        return this.srcServerPass;
    }
    
    public void setSrcServerPass(String srcServerPass) {
        this.srcServerPass = srcServerPass;
    }
    public String getSrcServerPath() {
        return this.srcServerPath;
    }
    
    public void setSrcServerPath(String srcServerPath) {
        this.srcServerPath = srcServerPath;
    }
    public String getDestServerUrl() {
        return this.destServerUrl;
    }
    
    public void setDestServerUrl(String destServerUrl) {
        this.destServerUrl = destServerUrl;
    }
    public String getDestServerUser() {
        return this.destServerUser;
    }
    
    public void setDestServerUser(String destServerUser) {
        this.destServerUser = destServerUser;
    }
    public String getDestServerPass() {
        return this.destServerPass;
    }
    
    public void setDestServerPass(String destServerPass) {
        this.destServerPass = destServerPass;
    }
    public String getDestServerPath() {
        return this.destServerPath;
    }
    
    public void setDestServerPath(String destServerPath) {
        this.destServerPath = destServerPath;
    }
    public BigDecimal getDestSecureCon() {
        return this.destSecureCon;
    }
    
    public void setDestSecureCon(BigDecimal destSecureCon) {
        this.destSecureCon = destSecureCon;
    }
    public BigDecimal getStatus() {
        return this.status;
    }
    
    public void setStatus(BigDecimal status) {
        this.status = status;
    }
    public BigDecimal getSrcSecureCon() {
        return this.srcSecureCon;
    }
    
    public void setSrcSecureCon(BigDecimal srcSecureCon) {
        this.srcSecureCon = srcSecureCon;
    }
    public Set getFtpJobUserMappings() {
        return this.ftpJobUserMappings;
    }
    
    public void setFtpJobUserMappings(Set ftpJobUserMappings) {
        this.ftpJobUserMappings = ftpJobUserMappings;
    }
    public Set getFtpExceptionses() {
        return this.ftpExceptionses;
    }
    
    public void setFtpExceptionses(Set ftpExceptionses) {
        this.ftpExceptionses = ftpExceptionses;
    }




}


